redis-cache:
  serviceName: user
  redis:
    host: '127.0.0.1'
    port: 6379
    password: 'chirag1234'
  serviceCaches:
    cache1:
      ttl: 600
    cache2:
      ttl: 60
  globalCaches:
    cache1:
      ttl: 60
log4js:
  appenders:
    file:
      type: file
      filename: logs/dreamdb-couchdb-gateway.log
      maxLogSize: 10485760
      numBackups: 3
    console:
      type: console
## 
  categories:
    default:
      appenders:
      - file
      level: INFO